#!/usr/bin/env bash
Info()
{ 
    echo -e '\033[1;34m'"Winello:\033[0m $*";
}

export PATH="$HOME/.local/share/osuconfig/wine-osu/bin:$PATH"
export WINEARCH=win64
if [ -d "$HOME/.local/share/wineprefixes/osu-wineprefix" ] ; then
export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix"
else
Info "Downloading and configuring Wineprefix: (take a coffee and wait e.e)"
Info "Remember to skip Wine Mono:"
WINEARCH=win64 WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" winetricks -q -f dotnet48 comctl32 vlgothic cjkfonts gdiplus_winxp
WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" winetricks -q win2k3
WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" wine reg add "HKEY_CURRENT_USER\\Software\\Wine" /v HideWineExports /t REG_SZ /d Y
export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" ; fi
osuinstall=$(</"$HOME/.local/share/osuconfig/osupath")
export OSUPATH="$osuinstall"

Info()
{
    echo -e '\033[1;34m'"Winello:\033[0m $*";
}

function help()
{
    Info "osu-wine: Runs osu!
    osu-wine --winecfg : Runs winecfg on the osu! Wineprefix
    osu-wine --winetricks: Install packages on osu! Wineprefix
    osu-wine --update: Updates wine-osu to latest version"
}

function update()
{   
    if [ "$CURRENTGLIBC" \< "$MINGLIBC" ]; then
    Info "1 - Ubuntu and derivatives (Linux Mint, Pop_OS, Zorin OS etc.)
          2 - openSUSE Tumbleweed
          3 - openSUSE Leap 15.3
          4 - exit"
    read -r -p "$(Info "Choose your distro: ")" distro
    case "$distro" in 
        '1')
        sudo apt update
        sudo apt install wine-osu
        rm -rf "$HOME/.local/share/osuconfig/wine-osu"
        cp -r /opt/wine-osu "$HOME/.local/share/osuconfig/wine-osu"
        Info "Update is completed!"
        ;;
        '2')
        zypper refresh
        zypper install wine-osu
        rm -rf "$HOME/.local/share/osuconfig/wine-osu"
        cp -r /opt/wine-osu "$HOME/.local/share/osuconfig/wine-osu" 
        Info "Update is completed!"
        ;;
        '3')
        zypper refresh
        zypper install wine-osu
        rm -rf "$HOME/.local/share/osuconfig/wine-osu"
        cp -r /opt/wine-osu "$HOME/.local/share/osuconfig/wine-osu"
        Info "Update is completed!"
        ;; 
	'4')
	exit 0
	;;
    esac
    else
    if [ "$LASTWINEVERSION" \!= "$WINEVERSION" ]; then
    wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1xgJIe18ccBx6yjPcmBxDbTnS1XxwrAcc' --output-document "/tmp/wine-osu-${WINEVERSION}-x86_64.pkg.tar.zst"
    tar -xf "/tmp/wine-osu-${WINEVERSION}-x86_64.pkg.tar.zst" -C "$HOME/.local/share/"
    rm -rf "$HOME/.local/share/osuconfig/wine-osu"
    mv "$HOME/.local/share/opt/opt/wine-osu" "$HOME/.local/share/osuconfig/"
    rm -rf "$HOME/.local/share/opt"
    rm -f "/tmp/wine-osu-${WINEVERSION}-x86_64.pkg.tar.zst"
    LASTWINEVERSION="$WINEVERSION"
    read -r -p "$(Info "Do you want to update wine-osu in Lutris too? (y/n)")" lutrupdate
    if [ "$lutrupdate" = 'y' ] || [ "$lutrupdate" = 'Y' ]; then
    rm -rf "$HOME/.local/share/lutris/runners/wine/wine-osu"
    cp -r "$HOME/.local/share/osuconfig/wine-osu" "$HOME/.local/share/lutris/runners/wine"
    else
    Info "Skipping...." ;fi
    Info "Update is completed!"
    else
    Error "Your wine-osu is already up-to-date!"
    fi
    fi
}

case "$1" in
  	'--winecfg')
    	WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" winecfg
	;;

	'--winetricks')
	WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix" winetricks "${@:2}"
	;;

	'--update')
	if [ "$EUID" -ne 0 ]; then Info "Run the script as root with sudo!" ;
	else
	update
	fi
	;;

	'')
	wine "$OSUPATH/osu!.exe"
	;;

	'help')
	help
	;;

esac
